const fortunes = [
  "Good things come to those who wait.",
  "A smile is your passport into the hearts of others.",
  "You will find joy in unexpected places.",
  "Opportunities are all around you.",
  "Your hard work will pay off soon.",
  "Embrace change; it leads to new beginnings.",
  "The best is yet to come.",
  "Happiness is a choice you make every day.",
  "Trust your intuition; it won't lead you astray.",
  "Believe in yourself, and others will too.",
  "A journey of a thousand miles begins with a single step.",
  "You are stronger than you think.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Your kindness will be repaid in unexpected ways.",
  "Today is a gift, that's why it's called the present.",
  "The universe is conspiring in your favor.",
  "You have the power to create the life you desire.",
  "Every setback is a setup for a comeback.",
  "You are capable of amazing things.",
  "The only way to do great work is to love what you do.",
  "When nothing goes right, go left.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Your future is as bright as your faith.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "Life is short. Smile while you still have teeth.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Happiness is not by chance, but by choice.",
  "Dream big and dare to fail.",
  "Your potential is endless.",
  "Do something today that your future self will thank you for.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "You are never too old to set another goal or to dream a new dream.",
  "Don't count the days, make the days count.",
  "Believe you can and you're halfway there.",
  "It always seems impossible until it's done.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "Don't watch the clock; do what it does. Keep going.",
  "The secret of getting ahead is getting started.",
  "Every day may not be good, but there is something good in every day.",
  "It's not whether you get knocked down, it's whether you get up.",
  "You don't have to be great to start, but you have to start to be great.",
  "You must do the things you think you cannot do.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Nothing in the world is more common than unsuccessful people with talent.",
  "The road to success and the road to failure are almost exactly the same.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
];

module.exports = fortunes;
